version: '3.8'

services:
  api:
    build: .
    container_name: api_gen_prompt_mood_chart
    ports:
      - "8009:8009"
    env_file:
      - .env
    environment:
      - EC2_BASE_URL=https://api.hey-watch.me
      - PYTHONUNBUFFERED=1
    volumes:
      - /home/ubuntu/data:/Users/kaya.matsumoto/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8009/health')"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s